import 'bootstrap'
import 'lightbox2/dist/js/lightbox-plus-jquery'
import './../js/app.js'
import './../js/formsContact.js'
// import 'normalize.css/normalize.css'
// import './../fontawesome/css/all.min.css'
// import 'bootstrap/dist/css/bootstrap.css'
// import 'aos/dist/aos.css'
// import './../css/app.css'
